# version: '3'

# services:
#   # Student_Enroll_Grade_System
#   final:
#     image: student-backend:latest
#     container_name: student-backend
#     restart: always
#     ports:
#       - "8001:8000"
#     environment:
#       - DEBUG=False
#       - JWT_SECRET_KEY='django-insecure-@%babz@u@5_=&75(em@s+m1&v0v#r(b5eyo*z4jq#n1&uw+7g='
#     volumes:
#       - student_data:/app/data
#       - student_static:/app/static
#       - student_media:/app/media

#   # Box
#   box_back:
#     image: box-backend:latest
#     container_name: box-backend
#     restart: always
#     ports:
#       - "8002:8000"
#     environment:
#       - DEBUG=False
#     volumes:
#       - box_data:/app/data
#       - box_static:/app/static
#       - box_media:/app/media

#   # P2P
#   P2P:
#     image: p2p-backend:latest
#     container_name: p2p-backend
#     restart: always
#     ports:
#       - "5001:5000"
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Production
#     volumes:
#       - p2p_data:/app/data
#       - p2p_static:/app/wwwroot


#   # Nginx服务
#   nginx:
#     image: nginx:alpine
#     container_name: nginx-gateway
#     ports:
#       - "80:80"
#       - "443:443"  # 如果启用HTTPS
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#       - ./nginx/ssl:/etc/nginx/ssl  # 如果启用HTTPS
#       # 静态文件挂载
#       - /var/www/student:/usr/share/nginx/html/student
#       - /var/www/box:/usr/share/nginx/html/box
#       - /var/www/p2p:/usr/share/nginx/html/p2p
#     depends_on:
#       - final
#       - box_back
#       - P2P
#     restart: always

# volumes:
#   student_data:
#   student_static:
#   student_media:
#   box_data:
#   box_static:
#   box_media:
#   p2p_data:
#   p2p_static:


version: '3'

services:
  # Student_Enroll_Grade_System
  final:
    image: student-backend:latest
    container_name: student-backend
    restart: always
    ports:
      - "8001:8000"
    environment:
      - DEBUG=True
      - JWT_SECRET_KEY='django-insecure-@%babz@u@5_=&75(em@s+m1&v0v#r(b5eyo*z4jq#n1&uw+7g='
      - ALLOWED_HOSTS=localhost,127.0.0.1,final,nginx,nginx-gateway,13.238.120.184,*
      - CORS_ALLOWED_ORIGINS=http://localhost,http://127.0.0.1,http://13.238.120.184
      - CORS_ALLOW_ALL_ORIGINS=True
      - PYTHONUNBUFFERED=1 # 显示更多日志信息
    volumes:
      - student_data:/app/data
      - student_static:/app/static
      - student_media:/app/media

  # Box
  box_back:
    image: box-backend:latest
    container_name: box-backend
    restart: always
    ports:
      - "8002:8000"
    environment:
      - DEBUG=False
    volumes:
      - box_data:/app/data
      - box_static:/app/static
      - box_media:/app/media

  # P2P
  P2P:
    image: p2p-backend:latest
    container_name: p2p-backend
    restart: always
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - p2p_data:/app/data
      - p2p_static:/app/wwwroot


  # Nginx服务
  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "80:80"
      - "443:443"  # 如果启用HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl  # 如果启用HTTPS
      # 静态文件挂载
      - /var/www/student:/usr/share/nginx/html/student
      - /var/www/box:/usr/share/nginx/html/box
      - /var/www/p2p:/usr/share/nginx/html/p2p
    depends_on:
      - final
      - box_back
      - P2P
    restart: always

volumes:
  student_data:
  student_static:
  student_media:
  box_data:
  box_static:
  box_media:
  p2p_data:
  p2p_static:
