version: '3'

services:
  # Student_Enroll_Grade_System
  final:
    image: student-backend:latest
    container_name: student-backend
    restart: always
    ports:
      - "8001:8000"
    environment:
      - DEBUG=False
      - JWT_SECRET_KEY=your_secret_key
    volumes:
      - student_data:/app/data
      - student_static:/app/static
      - student_media:/app/media

  front_end:
    image: student-frontend:latest
    container_name: student-frontend
    restart: always
    depends_on:
      - final

  # Box
  box_back:
    image: box-backend:latest
    container_name: box-backend
    restart: always
    ports:
      - "8002:8000"
    environment:
      - DEBUG=False
    volumes:
      - box_data:/app/data
      - box_static:/app/static
      - box_media:/app/media

  box_show:
    image: box-frontend:latest
    container_name: box-frontend
    restart: always
    depends_on:
      - box_back

  # P2P
  P2P:
    image: p2p-backend:latest
    container_name: p2p-backend
    restart: always
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - p2p_data:/app/data
      - p2p_static:/app/wwwroot

  p2p-client:
    image: p2p-frontend:latest
    container_name: p2p-frontend
    restart: always
    depends_on:
      - P2P

  # Nginx服务
  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "80:80"
      - "443:443"  # 如果启用HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl  # 如果启用HTTPS
      # 静态文件挂载
      - student_static:/var/www/student/static
      - student_media:/var/www/student/media
      - box_static:/var/www/box/static
      - box_media:/var/www/box/media
      - p2p_static:/var/www/p2p/static
    depends_on:
      - front_end
      - final
      - box_show
      - box_back
      - p2p-client
      - P2P
    restart: always

volumes:
  student_data:
  student_static:
  student_media:
  box_data:
  box_static:
  box_media:
  p2p_data:
  p2p_static: